### ISSUE TITLE
Not able to install the oci-python-sdk in centOS 6

### ISSUE THREAD

**Issue by wangzhihaocom** [oracle/oci-python-sdk#281] opened 2020-08-27 21:28 UTC
Hi,
This is Wally, from 8x8
I am having an issue to install the oci-python-sdk in centOS6
In centOS 7, it works fine just with "pip install oci" , but in centOS6, did not work. 

I have talked to Anoop Srivastava about this, and he told me that it seems to be a known issue on centOS 6 , dev team is working on getting a published fix on it. He wants me to open an issue here, so that I can get a quick response.

If there is any update regarding this fix, please let me kow

Thanks
Wally

**Comment by anosriva** [comment] 2020-08-28 16:33
Hi Wally - Found some more info on this
I checked and there is an issue already on this
https://github.com/oracle/oci-python-sdk/issues/108

GitHubGitHub
Install fails with cryptography 2.6 · Issue #108 · oracle/oci-python-sdk
https://github.com/pyca/cryptography/issues/4789

Looks to be a python pip issue as is pointed in these threads
Can you check with Python 3.4 as is suggested in the issue and try again
It should work

**Comment by jodoglevy** [comment] 2020-09-08 23:49
Closing this, as it sounds like this is a duplicate of #108.

If the suggestions by @anosriva above / in #108 don't resolve the issue for you, please feel free to reopen this ticket

**Closed by jodoglevy** 2020-09-08 23:49 UTC
