### ISSUE TITLE
output of list_objects : objects size,time_created,md5 are showing null when using python sdk

### ISSUE THREAD

**Issue by vipmike007** [oracle/oci-python-sdk#91] opened 2018-12-03 05:45 UTC
Hi, this issue is reported in https://github.com/oracle/oci-python-sdk/issues/90. but it has been closed but issue is still here.

From https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/object_storage/client/oci.object_storage.ObjectStorageClient.html#oci.object_storage.ObjectStorageClient.list_objects  we can see it's return value 

Returns: | A Response object with data of type ListObjects
-- | --

Here is my output of the return, we can see object_size,time_created,md5 are showing null instead of a actual value. Can you help to view this issue again?
{
"next_start_with": null,
"objects": [
{
"md5": null,
"name": "1487902706.jpg",
"size": null,
"time_created": null
},
{
"md5": null,
"name": "48132889.jpg",
"size": null,
"time_created": null
}
],
"prefixes": null
}

**Comment by jodoglevy** [comment] 2018-12-03 06:54
Hi, I'm going to this close this since its a dupe of #90. Will respond on that issue.

**Closed by jodoglevy** 2018-12-03 06:54 UTC
