### ISSUE TITLE
yum check-update throws an error

### ISSUE THREAD

**Issue by jazzl0ver** [oracle/oci-python-sdk#520] opened 2023-02-28 15:36 UTC
Hi,

Not sure this is the right place for this, but I wasn't able to find a better approach. Oracle's support just pisses me off with no ETA on the solution.
```
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

$ sudo yum check-update
Loaded plugins: langpacks, post-transaction-actions, ulninfo
Update notice ELBA-2023-12138 (from ol7_developer) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the ol7_developer repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
Update notice ELBA-2023-12139 (from ol7_developer) is broken, or a bad duplicate, skipping.
```
According to https://linux.oracle.com/errata/ELBA-2023-12138.html and https://linux.oracle.com/errata/ELBA-2023-12139.html, this is about the following packages:
```
$ rpm -qa|grep python36-oci
python36-oci-cli-3.23.1-1.el7.noarch
python36-oci-sdk-2.93.0-1.el7.x86_64
```
Is there a chance to fix it quickly. I have yum-cron package installed and it sends me an error letter every hour :(

**Comment by KartikShrikantHegde** [comment] 2023-03-14 20:37
Hi @jazzl0ver , is this an autonomous linux instance where you are seeing the error?

**Comment by jazzl0ver** [comment] 2023-03-15 07:12
hi @KartikShrikantHegde . what do you mean by "autonomous linux instance"?

**Comment by jazzl0ver** [comment] 2023-03-15 07:38
now it yells about:
```Update notice ELBA-2023-12149 (from ol7_developer) is broken, or a bad duplicate, skipping.
You should report this problem to the owner of the ol7_developer repository.
To help pinpoint the issue, please attach the output of "yum updateinfo --verbose" to the report.
Update notice ELBA-2023-12151 (from ol7_developer) is broken, or a bad duplicate, skipping.```

**Comment by KartikShrikantHegde** [comment] 2023-03-20 16:16
Hi @jazzl0ver , could you please send me an email (kartik.hegde@oracle.com) with SR#? I would need the SR# to work with our engineers.

**Comment by jazzl0ver** [comment] 2023-03-20 16:22
> Hi @jazzl0ver , could you please send me an email ([kartik.hegde@oracle.com](mailto:kartik.hegde@oracle.com)) with SR#? I would need the SR# to work with our engineers.

sent

**Comment by KartikShrikantHegde** [comment] 2023-03-21 15:54
Hi @jazzl0ver ,

The support team has informed me that the issue has been resolved and the SR# is updated as well. Please continue to work with the Oracle support team if you have more questions. Since the issue is not related to the GitHub repository in question, I will be closing this ticket.

Thanks.

**Closed by KartikShrikantHegde** 2023-03-21 15:54 UTC
Labels: SDK
