### ISSUE TITLE
ResourceWarning: unclosed socket.socket

### ISSUE THREAD

**Issue by tedpearson** [oracle/oci-python-sdk#110] opened 2019-03-09 05:15 UTC
Hey there guys,

I've run into an interesting warning using the compute api on python 3.7. I'm just running simple apis like: `compute.update_image(image_ocid, UpdateImageDetails(defined_tags=defined_tags))` but I'm seeing this error (produced using `import tracemalloc; tracemalloc.start()` to find where the socket was created):
```
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.15.15.88', 61087), raddr=('129.146.14.197', 443)>
  <snipped my line of code here>
Object allocated at (most recent call last):
  File "/Users/ted/.local/share/virtualenvs/<my library snipped>/lib/python3.7/site-packages/oci/_vendor/urllib3/util/connection.py", lineno 68
    sock = socket.socket(af, socktype, proto)
```

I've traced the call back to this method by editing the vendored connection.py to throw an error. If I just add a `self.session.close` just before the `return Response` in this method, my code still works and the ResourceWarning no longer appears. I can't say if that's the correct place to close things, but I wanted to report the ugly-looking warning.

For reference, I am currently using `oci==2.2.1`.

https://github.com/oracle/oci-python-sdk/blob/2ad0d15d092adfda0fd2369c7c1ee7c55d44d005/src/oci/base_client.py#L324

**Comment by tedpearson** [comment] 2019-03-09 05:33
While I'm here I'll just pile this other warning into a comment... 
```
/Users/ted/.local/share/virtualenvs/<snip>/lib/python3.7/site-packages/oci/_vendor/requests/models.py:181: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(hook, collections.Callable):
```

**Comment by arthall** [comment] 2019-03-11 15:10
Thank you, @tedpearson, for raising this issue.

Concerning the second warning message about collections, that is due to the version of Requests that we vendor.  Requests has addressed it with version 2.19.0 and we are currently preparing a release with version 2.21.0 of Requests.

**Comment by arthall** [comment] 2019-03-13 18:09
@tedpearson I believe I'm missing something here.  Do you have a short sample program which produces the warning, "ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.15.15.88', 61087), raddr=('129.146.14.197', 443)>"?  I have tried to reproduce the warning in Python 3.5.1 and Python 3.7.2 with the currently vendored packages and the updated packages.

The base_client should be holding open sockets because it uses connection pools, but everything should be cleaned up when a client is no longer needed.

**Comment by tedpearson** [comment] 2019-03-13 21:19
Hey Art, previously it was reproducible every time I ran some simple code, and now I can't reproduce at all either. I'm not sure what changed. I guess you can close this, and if it reoccurs I will remember to make a test case for you.

**Comment by arthall** [comment] 2019-03-14 13:45
Thanks @tedpearson.  I'm closing the issue for now.

**Closed by arthall** 2019-03-14 13:45 UTC
