### ISSUE TITLE
Missing network information when ran against specific compartment

### ISSUE THREAD

**Issue by NullARC** [oracle/oci-python-sdk#145] opened 2019-07-23 12:49 UTC
If showoci.py is ran against a compartment (with the -cp <compartmentName>) and if the network components reside in a different compartment, then the vnic information is left blank. 

output of  output file (in JSON format) where there is no network information

"vnic" : [
      {
         "id" : "ocid1.vnic.oc1.iad.axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
         "desc" : "10.xxx.xxx.xxx (Prv) - Primary ",
         "details" : {
            "private_ip" : "10.xxx.xxx.xxx",
            "display_name" : "10.xxx.xxx.xxx (Prv) - Primary ",
            "public_ip" : "",
            "skip_source_dest_check" : false,
            "is_primary" : true,
            "subnet" : "",
            "subnet_id" : "",
            "nsg_ids" : [],
            "nsg_names" : "",
            "vcn" : "",
            "dbdesc" : "10.xxxx.xxx.xxx (Prv) - Primary "
         }
      }
   ]

**Comment by NullARC** [comment] 2019-07-23 12:57
Setup:
Network compartment: has all network related resources (VCN, Subnets, DHCP options, gateways, security lists, network security groups, etc....)
VM Compartment: VMs are defined and use subnet from network compartment

**Comment by adizohar** [comment] 2019-07-23 13:36
Hi NullArc
This is a correct behaviour

if you run the showoci.py on specific compartment, it will only show you the components of the specific compartment
If the network reside on different compartment it won't extract it

What is exactly the issue ?

**Comment by NullARC** [comment] 2019-07-23 14:25
Hi Adi,
We are looking to use the output created from the showoci.py as an input file. We want to be able to capture all the information, but also limit the data captured to a targeted compartment.

If this is how the toolkit works, I'll pass this on and we'll work within these constraints.

Thanks for the insight.

**Comment by arthall** [comment] 2019-07-30 15:09
Closing this ticket since the program is working as designed.

**Closed by arthall** 2019-07-30 15:09 UTC
