### ISSUE TITLE
Pulling data with Virtual Network Client results in error in particular case

### ISSUE THREAD

**Issue by GrzegorzWysopal** [oracle/oci-python-sdk#425] opened 2022-01-26 22:15 UTC
Hi,

I am using API to retrieve some data from the tenancy.
I have already used API for Virtual Network Client to retrieve different data, and it worked.
However, in one particular example, I am getting an error.

When running this:

`network_client = oci.core.VirtualNetworkClient(config, signer=signer)
 network_client.get_networking_topology(tenancy.id).data`

I encounter this error:

`oci.exceptions.ServiceError: {'opc-request-id': '057B02AF5B224177921B81FA14F111FF/092CA4704E2B3584575BE12C31944A33/2297C5A5BA0B003A36E3B9586C18A586', 'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.', 'status': 404}`

The error occurs while retrieving data by `network_client.get_networking_topology(tenancy.id).data`.
At this moment, I do not have more ideas on how to solve this problem.
Please take a look and let me know whether there is a problem with my implementation or somewhere else.

Many thanks
Greg

**Comment by github-anurag** [comment] 2022-01-26 22:29
@GrzegorzWysopal 
The code looks correct implementation wise. The 404 is returned by the service team. We will check with them and get back to you on why this is failing.

**Comment by github-anurag** [comment] 2022-01-26 23:08
@GrzegorzWysopal 
Some additional check:-
Is the response from identity client you were using correct? That is, does is it return a valid Tenancy OCID? Also you can directly provide the compartment id from config instead of making another call to Identity get tenancy API.

**Comment by GrzegorzWysopal** [comment] 2022-01-26 23:21
Yes, the Tenancy OCID is correctly provided.

**Comment by Matt-Mcl** [comment] 2022-01-27 10:29
@github-anurag 

I also ran this as a raw request within python with the following code:
```python
endpoint = 'https://iaas.uk-london-1.oraclecloud.com/20160918/vcnTopology'
body = {
    'compartmentId': config['tenancy'],
}

response = requests.get(endpoint, params=body, auth=auth)

response.raise_for_status()
print(response.json())
```

The following output is shown: (tenancy OCID redacted)
```shell
Traceback (most recent call last):
  File "fireup.py", line 92, in <module>
    __main__()
  File "fireup.py", line 89, in __main__
    __exec_orchestrator()   
  File "fireup.py", line 80, in __exec_orchestrator
    response.raise_for_status()
  File "/home/opc/REPOS/fireup-repo/venv/lib64/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://iaas.uk-london-1.oraclecloud.com/20160918/vcnTopology?compartmentId=ocid1.tenancy.oc1..aaaetc
```

This is suggesting the API endpoint doesn't exists/isn't accepting traffic if I'm not mistaken?

**Comment by adizohar** [comment] 2022-01-27 12:58
Hi Matt

I face same issue , I tried as well oci-cli on both below occasions it throw errors on ashburn and london (Error 404)
oci network networking-topology get
oci network subnet-topology get

We will advise the service team for below APIs:
https://iaas.{region}.oraclecloud.com/20160918/subnetTopology
https://iaas.{region}..oraclecloud.com/20160918/networkingTopology

**Comment by github-anurag** [comment] 2022-01-27 18:59
@Matt-Mcl 
The API you referred to was [GetVcnTopology](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/VcnTopology/GetVcnTopology). However, @GrzegorzWysopal is using [GetNetworkingTopology](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/NetworkingTopology/GetNetworkingTopology)

**Comment by github-anurag** [comment] 2022-01-27 20:16
@GrzegorzWysopal 
Looks like there is an issue with the service endpoint being picked up here. We have raised an issue with the concerned team. In the meanwhile, can you try using the following workaround:-
```
network_client = oci.core.VirtualNetworkClient(config, signer=signer) 

# Replace us-phoenix-1 with the region you intend to work on
network_client.base_client.endpoint = "https://vnca-api.us-phoenix-1.oci.oraclecloud.com"

network_client.get_networking_topology(tenancy.id).data
```

**Comment by Matt-Mcl** [comment] 2022-01-28 07:59
@github-anurag 

Correct - my bad. Thanks for the workaround!

Should mention that Greg and I are both working on the same project - which is why I'm active on the thread.

**Comment by GrzegorzWysopal** [comment] 2022-01-28 10:59
@github-anurag Thank you for your help. The workaround actually works!

**Comment by dralquinta** [comment] 2022-02-09 19:57
We are hitting a regression when using this workaround on a Cloud Shell based environment (by using delegation token). 

I'm quoting the update I made on issue: https://github.com/oracle/oci-python-sdk/issues/429 where we explain the regression in more detail

We were able to pin down the issue. It relates to the way the signer is created. When using a delegation token, then the workaroiund given on https://github.com/oracle/oci-python-sdk/issues/425 goes haywire as it finds a mismatch on the region and fails.

We've prepared a test case, which is available on this repo, which isolates the problem. Ref: https://github.com/dralquinta/bug429

To reproduce:

Download the main branch from [here](https://github.com/dralquinta/bug429/archive/refs/heads/main.zip)
Open a Cloud Shell and copy main.zip into the cloud shell
Unzip the file main.zip
Execute ./test.sh -dt
Error will pop up after a while
We're making intensive use of similar stuff on other parts of our code, however as this is hitting directly the API endpoint, we suspect that fixing what's reported on https://github.com/oracle/oci-python-sdk/issues/425 will subsequently fix this as well.

**Comment by atomicbeecz** [comment] 2023-02-21 14:08
Hello, is there any workaround for this issue? I'm getting 404 as well for get VCN ID:

`oci.exceptions.ServiceError: {'target_service': 'virtual_network', 'status': 404, 'code': 'NotAuthorizedOrNotFound', 'opc-request-id': '2E6F90B56B504C03A91230C5A69DA536/42889A8EF3599DCA50FFD1BEFE2E8AD3/676A49CBABB1C836D37A8BDA972E790D', 'message': 'Authorization failed or requested resource not found.', 'operation_name': 'get_vcn', 'timestamp': '2023-02-21T14:01:28.752075+00:00', 'client_version': 'Oracle-PythonSDK/2.93.0', 'request_endpoint': 'GET https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns/ocid1.vcn.oc1.iad.amaaaaaad2zjmiaa4wuz57jerwktysn5oigsrgzmrw7st27bbnbbviaczzdq', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/iaas/20160918/Vcn/GetVcn for details on this operation's requirements. If you are unable to resolve this virtual_network issue, please contact Oracle support and provide them this full error message."}`

**Comment by KartikShrikantHegde** [comment] 2023-02-22 15:50
Hi @atomicbeecz ,

Can you try this workaround and see if it works? https://github.com/oracle/oci-python-sdk/issues/425#issuecomment-1023603057

**Comment by KartikShrikantHegde** [comment] 2023-02-22 15:58
Hi @atomicbeecz , can you please create a new issue? seems like your error is not related to the ongoing discussion on this thread but a different issue with get_vcn API. We will triage it separately and get the right team to look at it. Thanks!

**Comment by atomicbeecz** [comment] 2023-02-22 20:02
@github-anurag @KartikShrikantHegde In the end the problem was elsewhere (leftovers in bitbucket) so sorry for confusion.

**Comment by KartikShrikantHegde** [comment] 2023-03-09 19:14
Thanks @atomicbeecz , I will be closing this ticket.

@GrzegorzWysopal @dralquinta and @Matt-Mcl , we will keep the https://github.com/oracle/oci-python-sdk/issues/429 open.

**Closed by KartikShrikantHegde** 2023-03-09 19:14 UTC
Labels: Networking
