### ISSUE TITLE
config profile_name doesn't allow upper case with dashes

### ISSUE THREAD

**Issue by mannyreds11** [oracle/oci-python-sdk#191] opened 2019-11-25 16:12 UTC
this works:
```
[test-1]
user=ocid1.user.oc1..XXX
fingerprint=XX:YY
key_file=~/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..XXX
region=us-ashburn-1
```
```
>>> config = from_file(file_location="~/.oci/config", profile_name="test-1")
```
this doesn't:
```
➜  ~ cat ~/.oci/config
[TEST-1]
user=ocid1.user.oc1..XXX
fingerprint=XX:YY:...
key_file=~/.oci/oci_api_key.pem
tenancy=ocid1.tenancy.oc1..XXX
region=us-ashburn-1
```
```
>>> config = from_file(file_location="~/.oci/config", profile_name="TEST-1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/oci/config.py", line 80, in from_file
    raise ProfileNotFound("Profile '{}' not found in config file {}".format(profile_name, expanded_file_location))
oci.exceptions.ProfileNotFound: Profile 'TEST-1' not found in config file ~/.oci/config
```

**Comment by bhagwatvyas** [comment] 2020-04-08 21:27
Hi @mannyreds11, thank for for raising this issue. I tried to use your examples but cannot reproduce the error. Are you still facing this issue?

**Comment by bhagwatvyas** [comment] 2020-04-29 22:34
Hi @mannyreds11, I wanted to reach out to you if you had a chance to take a look at this issue.

**Comment by bhagwatvyas** [comment] 2020-05-06 20:37
Closing this issue for now, please feel free to comment if you run into this issue again.

**Closed by bhagwatvyas** 2020-05-06 20:37 UTC
Labels: SDK

**Comment by pajuscz** [comment] 2022-02-02 02:30
'-' dash or '_' underscore is apparently illegal character in oci profile name. Change your profile name to 'TEST1' and use it without special characters
