### ISSUE TITLE
Request Header Fields Too Large

### ISSUE THREAD

**Issue by Strongarm1** [oracle/oci-python-sdk#357] opened 2021-06-09 14:54 UTC
Getting this on several spots when using the showoci script.
Under "Compute...'
--> Autoscaling              <-- 
Error in ShowOCIService:__load_core_compute_autoscaling: {'opc-request-id': 'E074587D41AD4F75BBE9F75C2AF713C6/6703DFEBFB456C1F972CD0D6FCE520F2/89F690971C5E3749033B00F1B56A4F7F', 'code': None, 'message': '<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>', 'status': 431}

--> OCVS Native - VMWare     <-- 
Error in ShowOCIService:__load_paas_ocvs: {'opc-request-id': '6CC5F05240D6429F9DB8A4946ADA6AC7/0F9C6001541F49A1BF7B921268262608/692E2FCB470160FF8576F1238F22D08B', 'code': None, 'message': '<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>', 'status': 431}
Don't think we have any.

--> Big Data Services        <-- 
Error in ShowOCIService:__load_data_ai_bds: {'opc-request-id': 'A68EB1776A12454FB5C3C0CEE6F8278B/8EBD0B8E53C304A1BD6B168F6A18675A/0B70B6EDA0E874A33938A53A3851193A', 'code': None, 'message': '<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>', 'status': 431}
Don't think we have any.

**Comment by adizohar** [comment] 2021-06-09 20:02
Hi
Did you upgrade to the latest OCI SDK and latest showoci ? 
pip3 install --upgrade oci

and download the showoci scripts

**Comment by Strongarm1** [comment] 2021-06-10 01:34
Hmm, I did download the latest showoci but I didn’t try the upgrade. Will try that tomorrow.

**Comment by Strongarm1** [comment] 2021-06-10 19:07
I updated to the latest version
Showoci Version : 21.06.02
OCI SDK Version : 2.39.1

Still occurring:
--> Autoscaling              <-- 
Error in ShowOCIService:__load_core_compute_autoscaling: {'opc-request-id': 'EBC4AC39380A4C2187E365C84FF91FB1/B4639A212008779644E1260975EB1D31/B1AD95C03DB8AADF43801449CCF01344', 'code': None, 'message': '<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>', 'status': 431}

**Comment by adizohar** [comment] 2021-06-10 20:02
What is the platform you are running - windows / linux and what version
what is the python version  ?

**Comment by Strongarm1** [comment] 2021-06-14 22:36
Using the OCI console. 
Default Python version.
Both us-asburn-1 and us-phoenix-1

**Comment by adizohar** [comment] 2021-06-15 01:04
Hi Strongarm1
Appreciate the feedback, it looks like the issue is with the Instance Principals With Delegation Token which inside cloud shell.
We will open ticket to the required service team to fix this issue

Below the services we found, maybe some more exist:
oci autoscaling configuration list (autoscaling.list_auto_scaling_configurations)
oci bds instance list (bds_client.list_bds_instances)
oci ocvs sddc list (ocvs_client.list_sddcs)

**Comment by adizohar** [comment] 2021-07-29 17:46
Hi Strongarm1
Service team fixed the Error 431 on Autoscale and VMWare
Pending Big Data, will update you once this done
For your info

**Comment by adizohar** [comment] 2021-08-05 13:56
Hi Strongarm1
The issue has been fixed, can you please check and confirm ? 
Thank you

**Comment by jodoglevy** [comment] 2021-08-10 23:50
@Strongarm1 I'm closing this because we believe this issue has been resolved, but feel free to reopen this if you are still experiencing issues

**Closed by jodoglevy** 2021-08-10 23:50 UTC
